<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/1/15
 * Time: 10:57
 */

namespace App\Server\Investment\Dao;

use App\Model\InvestmentRule;

class InvestmentRuleDao extends  InvestmentRule
{


   public function getRecordByCondition($where){

       return parent::getRecordByCondition($where);
   }

    //根据条件获取数据
    public function getAllRecords($where)
    {
        $InvestmentRule = parent::getAllRecords($where)->toArray(); // TODO: Change the autogenerated stub

        if($InvestmentRule){
                 foreach ($InvestmentRule as $key=>$value){
                     $InvestmentRule[$key]['invest_time'] = $value['invest_time']/86400;
                 }
        }
        return $InvestmentRule;
    }


    public function getInvestSetMeal($where){
        $InvestmentRule = parent::getRecordByCondition($where)->toArray(); // TODO: Change the autogenerated stub

        if($InvestmentRule){
            foreach ($InvestmentRule as $key=>$value){
                $InvestmentRule[$key]['invest_time'] = $value['invest_time']/86400;
            }
        }
        return $InvestmentRule;

    }

    public function updateInvestRule($where,$data){


        return parent::updateInvestRule($where,$data);

    }

    /* 删除数据
     *
     *
     */
    public function deleInvestRule($where){
        $data =['is_usable'=>0];
        return parent::updateInvestStatue($where,$data);

    }




    /* 获取一条数据
     *
     *
     */
    public function getOneInvestRule($id){

        return parent::getOneRecord($id);

                     }

         //将数据入库
        public function insertInvestRule($data){

            $data['invest_time']= $data['invest_time']*86400;

             return  parent::insertData($data);
                                                 }

}