<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/1/15
 * Time: 10:57
 */

namespace App\Server\Investment\Dao;

use  App\Model\InvestmentType;

class InvestmentTypeDao extends  InvestmentType
{

    public $id=null;

      //获取投资的类型
    public function getRecordByCondition($where)
     {
        return parent::getRecordByCondition($where); // TODO: Change the autogenerated stub
     }

     //后台获取数据类型
     public function getInvestType(){

         $where = ['is_usable'=>1];

       return parent::getInvestTypeWithCoinName($where);


     }


     public function insertInvest($data){

           return parent::insertInvest($data);

     }


}